export const productAction = {
    FETCHING: 'FETCHING',
    FETCHING_SUCCESSFUL: 'FETCHING_SUCCESSFUL',
    FETCHING_FAILED: 'FETCHING_FAILED',
    ADD_TO_CARD: 'ADD_TO_CARD',
    REMOVE_FROM_CARD: 'REMOVE_FROM_CARD',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
}